// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class player : role
///<<< BEGIN WRITING YOUR CODE player
///<<< END WRITING YOUR CODE
{
	private int CARD_COUNT_PLAYER_START = 0;
	public void _set_CARD_COUNT_PLAYER_START(int value)
	{
		CARD_COUNT_PLAYER_START = value;
	}
	public int _get_CARD_COUNT_PLAYER_START()
	{
		return CARD_COUNT_PLAYER_START;
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

